name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

env:
  RUSTFLAGS: -D warnings

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fromTag: v0.1.5
          toTag: v0.1.6
          commitMode: true
          configurationJson: |
            {
              "tag_resolver": {
                "pattern": "v(.+)"
              }
            }
      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{steps.github_release.outputs.changelog}}
          tag_name: v0.1.6
          name: v0.1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
