name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

env:
  RUSTFLAGS: -D warnings

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable-x86_64-pc-windows-msvc
          - stable-x86_64-apple-darwin
          - stable-x86_64-unknown-linux-gnu
          - beta-x86_64-unknown-linux-gnu
          - nightly-x86_64-unknown-linux-gnu
        include:
          - toolchain: stable-x86_64-pc-windows-msvc
            os: windows-latest
          - toolchain: stable-x86_64-apple-darwin
            os: macos-latest
          - toolchain: stable-x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - toolchain: beta-x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - toolchain: nightly-x86_64-unknown-linux-gnu
            os: ubuntu-latest
    name: Check on ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rust-toolchain ( ${{ matrix.toolchain }} )
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: "`cargo check`"
        run: cargo check --all-targets --all-features
      - name: "`cargo deny`"
        run: cargo deny check
      - name: "`cargo test`"
        run: cargo test --no-fail-fast --verbose --locked
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: "`cargo clippy`"
        run: cargo clippy --all-targets --all-features

