name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'release')
    steps:
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Extract version from PR title
        id: tag
        run: echo "${{ github.event.pull_request.title }}" | awk '{print "name="  $2}' >> "$GITHUB_OUTPUT"
      - name: Push a new tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          custom_tag: ${{ steps.tag.outputs.name }}
          tag_prefix: ""
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.name }}
          name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          token: ${{ steps.generate-token.outputs.token }}
